'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'
import { logAuditEvent } from '@/lib/audit'
import { notifyStudentLifecycle } from '@/services/notifications'
import type { TrainingStatus, AccountStatus } from '@/types'

export interface AddStudentInput {
  full_name: string
  phone: string
  email: string
  password?: string
  license_category: string
  blood_type?: string
  driving_school_id?: string
}

function generatePassword(): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'
  return Array.from({ length: 10 }, () => chars[Math.floor(Math.random() * chars.length)]).join('')
}

export async function addStudent(
  input: AddStudentInput
): Promise<{ error?: string; createdPassword?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: adminProfile } = await supabase
    .from('profiles')
    .select('role, driving_school_id')
    .eq('user_id', user.id)
    .single()

  if (!adminProfile) return { error: 'Profil introuvable.' }

  let schoolId: string
  if (adminProfile.role === 'school_admin') {
    if (!adminProfile.driving_school_id) return { error: 'Aucune auto-école liée à ce compte.' }
    schoolId = adminProfile.driving_school_id
  } else if (adminProfile.role === 'super_admin') {
    if (!input.driving_school_id) return { error: 'Veuillez sélectionner une auto-école.' }
    schoolId = input.driving_school_id
  } else {
    return { error: 'Accès refusé.' }
  }

  if (!input.email?.trim()) return { error: "L'email est obligatoire." }

  const isAutoGenerated = !input.password?.trim()
  const password = isAutoGenerated ? generatePassword() : input.password!.trim()

  const admin = createAdminClient()

  const { data: authData, error: authError } = await admin.auth.admin.createUser({
    email: input.email.trim(),
    password,
    email_confirm: true,
  })

  if (authError) {
    const msg = authError.message.includes('already registered')
      ? 'Cette adresse email est déjà utilisée.'
      : authError.message
    return { error: msg }
  }

  const authUserId = authData.user.id

  const { data: profileData, error: profileError } = await admin
    .from('profiles')
    .insert({
      user_id: authUserId,
      full_name: input.full_name.trim(),
      phone: input.phone?.trim() || null,
      role: 'student',
      driving_school_id: schoolId,
    })
    .select('id')
    .single()

  if (profileError) {
    await admin.auth.admin.deleteUser(authUserId)
    return { error: profileError.message }
  }

  const { error: studentError } = await admin.from('students').insert({
    driving_school_id: schoolId,
    profile_id:        profileData.id,
    full_name:         input.full_name.trim(),
    phone:             input.phone?.trim() || null,
    email:             input.email.trim(),
    license_category:  input.license_category,
    blood_type:        input.blood_type?.trim() || null,
  })

  if (studentError) {
    await admin.from('profiles').delete().eq('id', profileData.id)
    await admin.auth.admin.deleteUser(authUserId)
    return { error: studentError.message }
  }

  revalidatePath('/dashboard/students')
  return { createdPassword: isAutoGenerated ? password : undefined }
}

export async function updateTrainingStatus(
  studentId: string,
  status: TrainingStatus
): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles').select('role').eq('user_id', user.id).single()

  if (!profile) return { error: 'Profil introuvable.' }
  if (profile.role !== 'school_admin' && profile.role !== 'super_admin') return { error: 'Accès refusé.' }

  const { error } = await supabase
    .from('students')
    .update({ training_status: status, updated_at: new Date().toISOString() })
    .eq('id', studentId)

  if (error) return { error: "Mise à jour impossible." }

  revalidatePath('/dashboard/students')
  revalidatePath(`/dashboard/students/${studentId}`)
  return {}
}

export async function updateStudentInfo(
  studentId: string,
  data: { blood_type?: string }
): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles').select('role').eq('user_id', user.id).single()

  if (profile?.role !== 'school_admin' && profile?.role !== 'super_admin') return { error: 'Accès refusé.' }

  const { error } = await supabase
    .from('students')
    .update({ ...data, updated_at: new Date().toISOString() })
    .eq('id', studentId)

  if (error) return { error: error.message }

  revalidatePath('/dashboard/students')
  revalidatePath(`/dashboard/students/${studentId}`)
  return {}
}

export async function uploadMedicalDocument(
  formData: FormData
): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles')
    .select('role, driving_school_id')
    .eq('user_id', user.id)
    .single()

  if (!profile) return { error: 'Profil introuvable.' }
  if (profile.role !== 'school_admin' && profile.role !== 'super_admin') return { error: 'Accès refusé.' }

  const studentId = formData.get('student_id') as string
  const file = formData.get('file') as File

  if (!file || file.size === 0) return { error: 'Aucun fichier sélectionné.' }
  if (file.size > 10 * 1024 * 1024) return { error: 'Le fichier ne doit pas dépasser 10 Mo.' }

  if (profile.role === 'school_admin') {
    const { data: student } = await supabase
      .from('students')
      .select('driving_school_id')
      .eq('id', studentId)
      .single()
    if (!student || student.driving_school_id !== profile.driving_school_id) {
      return { error: 'Accès refusé.' }
    }
  }

  // Fixed path per student — upsert overwrites previous document regardless of format
  const storagePath = `${studentId}/medical-document`

  const { error: uploadError } = await supabase.storage
    .from('medical-documents')
    .upload(storagePath, file, { upsert: true, contentType: file.type })

  if (uploadError) return { error: uploadError.message }

  const { error: updateError } = await supabase
    .from('students')
    .update({ medical_document_url: storagePath, updated_at: new Date().toISOString() })
    .eq('id', studentId)

  if (updateError) return { error: updateError.message }

  revalidatePath('/dashboard/students')
  revalidatePath(`/dashboard/students/${studentId}`)
  return {}
}

// ── Lifecycle helpers ────────────────────────────────────────────────────────

async function requireLifecycleActor(): Promise<{
  error?: string
  userId?: string
  profileId?: string
  role?: string
  schoolId?: string | null
}> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, role, driving_school_id')
    .eq('user_id', user.id)
    .single()

  if (!profile) return { error: 'Profil introuvable.' }
  if (profile.role !== 'super_admin' && profile.role !== 'school_admin') {
    return { error: 'Accès refusé.' }
  }

  return {
    userId:    user.id,
    profileId: profile.id,
    role:      profile.role,
    schoolId:  profile.driving_school_id ?? null,
  }
}

async function verifySchoolOwnership(
  studentId: string,
  actor: { role: string; schoolId: string | null | undefined }
): Promise<{ error?: string; student?: { account_status: string; driving_school_id: string; email: string; full_name: string } }> {
  const admin = createAdminClient()
  const { data: student } = await admin
    .from('students')
    .select('account_status, driving_school_id, email, full_name')
    .eq('id', studentId)
    .single()

  if (!student) return { error: 'Élève introuvable.' }

  if (actor.role === 'school_admin') {
    if (!actor.schoolId || student.driving_school_id !== actor.schoolId) {
      return { error: "Accès refusé : cet élève n'appartient pas à votre auto-école." }
    }
  }

  return { student }
}

function revalidateStudentPaths(studentId: string) {
  revalidatePath('/dashboard/students')
  revalidatePath(`/dashboard/students/${studentId}`)
}

// ── Lifecycle mutations ──────────────────────────────────────────────────────

export async function suspendStudent(
  studentId: string,
  reason: string
): Promise<{ error?: string }> {
  if (!reason.trim()) return { error: 'La raison de la suspension est obligatoire.' }

  const actor = await requireLifecycleActor()
  if (actor.error) return { error: actor.error }

  const { error: ownerErr, student } = await verifySchoolOwnership(studentId, { role: actor.role!, schoolId: actor.schoolId })
  if (ownerErr) return { error: ownerErr }

  if (student!.account_status === 'suspended') {
    return { error: "Cet élève est déjà suspendu." }
  }

  const admin = createAdminClient()
  const { data: updated, error } = await admin
    .from('students')
    .update({
      account_status:    'suspended',
      suspension_reason: reason.trim(),
      archived_at:       null,
      archived_by:       null,
      archive_reason:    null,
      updated_at:        new Date().toISOString(),
    })
    .eq('id', studentId)
    .select('id')
    .single()

  if (error) return { error: error.message }
  if (!updated) return { error: 'Mise à jour impossible.' }

  await logAuditEvent({
    actorProfileId: actor.profileId!,
    actorUserId:    actor.userId!,
    actorRole:      actor.role!,
    action:         'student.suspended',
    entityType:     'student',
    entityId:       studentId,
    metadata: {
      student_id:       studentId,
      school_id:        student!.driving_school_id,
      reason:           reason.trim(),
      previous_status:  student!.account_status,
      new_status:       'suspended',
    },
  })

  try {
    await notifyStudentLifecycle({
      action:       'suspended',
      studentEmail: student!.email,
      studentName:  student!.full_name,
      reason:       reason.trim(),
    })
  } catch { /* non-fatal */ }

  revalidateStudentPaths(studentId)
  return {}
}

export async function archiveStudent(
  studentId: string,
  reason: string
): Promise<{ error?: string }> {
  if (!reason.trim()) return { error: "La raison de l'archivage est obligatoire." }

  const actor = await requireLifecycleActor()
  if (actor.error) return { error: actor.error }

  const { error: ownerErr, student } = await verifySchoolOwnership(studentId, { role: actor.role!, schoolId: actor.schoolId })
  if (ownerErr) return { error: ownerErr }

  if (student!.account_status === 'archived') {
    return { error: "Cet élève est déjà archivé." }
  }

  const now = new Date().toISOString()
  const admin = createAdminClient()
  const { data: updated, error } = await admin
    .from('students')
    .update({
      account_status:    'archived',
      archive_reason:    reason.trim(),
      archived_at:       now,
      archived_by:       actor.profileId,
      suspension_reason: null,
      reactivated_at:    null,
      reactivated_by:    null,
      updated_at:        now,
    })
    .eq('id', studentId)
    .select('id')
    .single()

  if (error) return { error: error.message }
  if (!updated) return { error: 'Mise à jour impossible.' }

  await logAuditEvent({
    actorProfileId: actor.profileId!,
    actorUserId:    actor.userId!,
    actorRole:      actor.role!,
    action:         'student.archived',
    entityType:     'student',
    entityId:       studentId,
    metadata: {
      student_id:       studentId,
      school_id:        student!.driving_school_id,
      reason:           reason.trim(),
      previous_status:  student!.account_status,
      new_status:       'archived',
    },
  })

  try {
    await notifyStudentLifecycle({
      action:       'archived',
      studentEmail: student!.email,
      studentName:  student!.full_name,
      reason:       reason.trim(),
    })
  } catch { /* non-fatal */ }

  revalidateStudentPaths(studentId)
  return {}
}

export async function reactivateStudent(
  studentId: string
): Promise<{ error?: string }> {
  const actor = await requireLifecycleActor()
  if (actor.error) return { error: actor.error }

  const { error: ownerErr, student } = await verifySchoolOwnership(studentId, { role: actor.role!, schoolId: actor.schoolId })
  if (ownerErr) return { error: ownerErr }

  if (student!.account_status === 'active') {
    return { error: "Cet élève est déjà actif." }
  }

  const previousStatus = student!.account_status as AccountStatus
  const now = new Date().toISOString()
  const admin = createAdminClient()
  const { data: updated, error } = await admin
    .from('students')
    .update({
      account_status:    'active',
      reactivated_at:    now,
      reactivated_by:    actor.profileId,
      suspension_reason: null,
      archived_at:       null,
      archived_by:       null,
      archive_reason:    null,
      updated_at:        now,
    })
    .eq('id', studentId)
    .select('id')
    .single()

  if (error) return { error: error.message }
  if (!updated) return { error: 'Mise à jour impossible.' }

  await logAuditEvent({
    actorProfileId: actor.profileId!,
    actorUserId:    actor.userId!,
    actorRole:      actor.role!,
    action:         'student.reactivated',
    entityType:     'student',
    entityId:       studentId,
    metadata: {
      student_id:       studentId,
      school_id:        student!.driving_school_id,
      previous_status:  previousStatus,
      new_status:       'active',
    },
  })

  try {
    await notifyStudentLifecycle({
      action:       'reactivated',
      studentEmail: student!.email,
      studentName:  student!.full_name,
    })
  } catch { /* non-fatal */ }

  revalidateStudentPaths(studentId)
  return {}
}

export async function getSignedDocumentUrl(
  studentId: string
): Promise<{ error?: string; url?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles')
    .select('role, driving_school_id, id')
    .eq('user_id', user.id)
    .single()

  if (!profile) return { error: 'Accès refusé.' }

  const { data: student } = await supabase
    .from('students')
    .select('medical_document_url, driving_school_id, profile_id')
    .eq('id', studentId)
    .single()

  if (!student?.medical_document_url) return { error: 'Aucun document trouvé.' }

  if (profile.role === 'school_admin' && student.driving_school_id !== profile.driving_school_id) {
    return { error: 'Accès refusé.' }
  }
  if (profile.role === 'student' && student.profile_id !== profile.id) {
    return { error: 'Accès refusé.' }
  }
  if (!['super_admin', 'school_admin', 'student'].includes(profile.role)) {
    return { error: 'Accès refusé.' }
  }

  const { data, error } = await supabase.storage
    .from('medical-documents')
    .createSignedUrl(student.medical_document_url, 3600)

  if (error || !data) return { error: error?.message ?? 'Impossible de générer le lien.' }
  return { url: data.signedUrl }
}
