'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'
import type { TrainingStatus } from '@/types'

export interface AddStudentInput {
  full_name: string
  phone: string
  email: string
  password?: string
  license_category: string
  blood_type?: string
  driving_school_id?: string
}

function generatePassword(): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'
  return Array.from({ length: 10 }, () => chars[Math.floor(Math.random() * chars.length)]).join('')
}

export async function addStudent(
  input: AddStudentInput
): Promise<{ error?: string; createdPassword?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: adminProfile } = await supabase
    .from('profiles')
    .select('role, driving_school_id')
    .eq('user_id', user.id)
    .single()

  if (!adminProfile) return { error: 'Profil introuvable.' }

  let schoolId: string
  if (adminProfile.role === 'school_admin') {
    if (!adminProfile.driving_school_id) return { error: 'Aucune auto-école liée à ce compte.' }
    schoolId = adminProfile.driving_school_id
  } else if (adminProfile.role === 'super_admin') {
    if (!input.driving_school_id) return { error: 'Veuillez sélectionner une auto-école.' }
    schoolId = input.driving_school_id
  } else {
    return { error: 'Accès refusé.' }
  }

  if (!input.email?.trim()) return { error: "L'email est obligatoire." }

  const isAutoGenerated = !input.password?.trim()
  const password = isAutoGenerated ? generatePassword() : input.password!.trim()

  const admin = createAdminClient()

  const { data: authData, error: authError } = await admin.auth.admin.createUser({
    email: input.email.trim(),
    password,
    email_confirm: true,
  })

  if (authError) {
    const msg = authError.message.includes('already registered')
      ? 'Cette adresse email est déjà utilisée.'
      : authError.message
    return { error: msg }
  }

  const authUserId = authData.user.id

  const { data: profileData, error: profileError } = await admin
    .from('profiles')
    .insert({
      user_id: authUserId,
      full_name: input.full_name.trim(),
      phone: input.phone?.trim() || null,
      role: 'student',
      driving_school_id: schoolId,
    })
    .select('id')
    .single()

  if (profileError) {
    await admin.auth.admin.deleteUser(authUserId)
    return { error: profileError.message }
  }

  const { error: studentError } = await admin.from('students').insert({
    driving_school_id: schoolId,
    profile_id:        profileData.id,
    full_name:         input.full_name.trim(),
    phone:             input.phone?.trim() || null,
    email:             input.email.trim(),
    license_category:  input.license_category,
    blood_type:        input.blood_type?.trim() || null,
  })

  if (studentError) {
    await admin.from('profiles').delete().eq('id', profileData.id)
    await admin.auth.admin.deleteUser(authUserId)
    return { error: studentError.message }
  }

  revalidatePath('/dashboard/students')
  return { createdPassword: isAutoGenerated ? password : undefined }
}

export async function updateTrainingStatus(
  studentId: string,
  status: TrainingStatus
): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles').select('role').eq('user_id', user.id).single()

  if (!profile) return { error: 'Profil introuvable.' }
  if (profile.role !== 'school_admin' && profile.role !== 'super_admin') return { error: 'Accès refusé.' }

  const { error } = await supabase
    .from('students')
    .update({ training_status: status, updated_at: new Date().toISOString() })
    .eq('id', studentId)

  if (error) return { error: "Mise à jour impossible." }

  revalidatePath('/dashboard/students')
  revalidatePath(`/dashboard/students/${studentId}`)
  return {}
}

export async function updateStudentInfo(
  studentId: string,
  data: { blood_type?: string; medical_document_url?: string }
): Promise<{ error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' }

  const { data: profile } = await supabase
    .from('profiles').select('role').eq('user_id', user.id).single()

  if (profile?.role !== 'school_admin' && profile?.role !== 'super_admin') return { error: 'Accès refusé.' }

  const { error } = await supabase
    .from('students')
    .update({ ...data, updated_at: new Date().toISOString() })
    .eq('id', studentId)

  if (error) return { error: error.message }

  revalidatePath('/dashboard/students')
  revalidatePath(`/dashboard/students/${studentId}`)
  return {}
}
