import type { Metadata, Viewport } from 'next'
import './globals.css'
import ServiceWorkerRegistration from '@/components/pwa/ServiceWorkerRegistration'

export const metadata: Metadata = {
  applicationName: 'SunuPermis',
  title:           'SunuPermis',
  description:     'Plateforme de gestion pour auto-écoles au Sénégal',
  // manifest link is auto-generated by app/manifest.ts
  appleWebApp: {
    capable:         true,
    statusBarStyle:  'default',
    title:           'SunuPermis',
  },
  formatDetection: { telephone: false },
}

export const viewport: Viewport = {
  themeColor:   '#131140',
  width:        'device-width',
  initialScale: 1,
  minimumScale: 1,
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className="h-full">
      <body className="h-full">
        <ServiceWorkerRegistration />
        {children}
      </body>
    </html>
  )
}
